# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  
  - logger: many_loggers # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - paths: default
  - hydra: default
  - experiment: gearnet_cbalm_cmlm   # experiment configs allow for version control of specific hyperparameters
  - callbacks: default

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default
  - _self_
  # debugging config (enable through command line, e.g. `python train.py debug=default)

extras:
  # disable python warnings if they annoy you
  ignore_warnings: False

  # ask user for tags if none are provided in the config
  enforce_tags: True

  # pretty print config tree at the start of the run using Rich library
  print_config: True

task:
  generator:
    max_iter: 10
    # strategy: mask_predict
    n_samples: 100
    temperature: 0.1
    tasks:
      full:
        name: full
        noise: full_mask
        contact: True
      # h1:
      #   name: h1
      #   noise: selected_mask
      #   mask: h1
      #   contact: True
      # h2:
      #   name: h2
      #   noise: selected_mask
      #   mask: h2
      #   contact: True
      h3:
        name: h3
        noise: selected_mask
        mask: h3
        contact: True
      # l1:
      #   name: l1
      #   noise: selected_mask
      #   mask: l1
      #   contact: True
      # l2:
      #   name: l2
      #   noise: selected_mask
      #   mask: l2
      #   contact: True
      # l3:
      #   name: l3
      #   noise: selected_mask
      #   mask: l3
      #   contact: True
      cdr:
        name: cdr
        noise: selected_mask
        mask: cdr_weights
        contact: True

data:
  max_tokens: 300 # set this to 300 for generating more than 1 sample

task_name: "eval_cbalm_sundae"
seed: 2023

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: None

